import type { Product } from '../types/product';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Ração Premium para Cães',
    imageUrl: '',
    price: 89.90,
    category: 'Alimentação',
    categoryKey: 'bone',
    description: 'Ração super premium com frango e arroz, rica em nutrientes essenciais para cães adultos.',
    rating: 5.0,
    reviewCount: '1.2k',
  },
  {
    id: '2',
    name: 'Arranhador para Gatos',
    imageUrl: '',
    price: 45.00,
    category: 'Brinquedos',
    categoryKey: 'music',
    description: 'Arranhador em sisal natural com plataforma elevada e brinquedo pendente.',
    rating: 5.0,
    reviewCount: '1.2k',
  },
  {
    id: '3',
    name: 'Cama Ortopédica Pet',
    imageUrl: '',
    price: 129.90,
    category: 'Acessórios',
    categoryKey: 'glasses',
    description: 'Cama com espuma ortopédica de alta densidade, ideal para pets idosos ou com dores articulares.',
    rating: 4.4,
    reviewCount: '1k',
  },
  {
    id: '4',
    name: 'Coleira Anti-Pulgas',
    imageUrl: '',
    price: 59.90,
    category: 'Acessórios',
    categoryKey: 'glasses',
    description: 'Coleira de proteção contra pulgas, carrapatos e mosquitos com duração de 8 meses.',
    rating: 4.8,
    reviewCount: '320',
  },
  {
    id: '5',
    name: 'Shampoo Veterinário',
    imageUrl: '',
    price: 34.90,
    category: 'Higiene & Saúde',
    categoryKey: 'heart',
    description: 'Shampoo hipoalergênico com aveia e aloe vera, indicado para peles sensíveis.',
    rating: 5.0,
    reviewCount: '1.2k',
  },
  {
    id: '6',
    name: 'Brinquedo Interativo Kong',
    imageUrl: '',
    price: 49.90,
    category: 'Brinquedos',
    categoryKey: 'music',
    description: 'Brinquedo de borracha resistente para recheio com petiscos, estimula o raciocínio.',
    rating: 4.8,
    reviewCount: '2.4k',
  },
  {
    id: '7',
    name: 'Bebedouro Automático',
    imageUrl: '',
    price: 79.90,
    category: 'Brinquedos',
    categoryKey: 'toy',
    description: 'Bebedouro com filtragem em cascata que incentiva o pet a beber mais água.',
    rating: 5.0,
    reviewCount: '1.1k',
  },
  {
    id: '8',
    name: 'Comedouro Inox Duplo',
    imageUrl: '',
    price: 39.90,
    category: 'Brinquedos',
    categoryKey: 'music',
    description: 'Comedouro duplo em aço inoxidável com base antiderrapante, fácil de higienizar.',
    rating: 5.0,
    reviewCount: '1.2k',
  },
];

export const sidebarCategories = [
  { key: 'all', label: 'Todos' },
  { key: 'glasses', label: 'Acessórios' },
  { key: 'toy', label: 'Brinquedos' },
  { key: 'bone', label: 'Alimentação' },
  { key: 'heart', label: 'Higiene & Saúde' },
];
